version: "3.9"

services:
  api:
    container_name: musix_api
    image: mcr.microsoft.com/dotnet/aspnet:5.0
    build:
      context: ./
    depends_on:
      - db
    ports:
      - "8080:80"

  db:
    container_name: musix_db
    image: mysql:latest
    restart: always
    #command: --default-authentiation-plugin=mysql_native-password
    build:
      context: ./Database
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "3306:3306" 
    volumes:
      - ./musix_db:/var/lib/mysql

volumes:
  musix_db: